# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Yan Can
tagline:             'Yan Can Code'
description:         'Learning to say "Hello World" in a multiverse of worlds.'
url:                 http://yancann.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jess Yan
  url:               https://yan-can.com
  email:             jessicayancan@gmail.com

# Custom vars
version:             1.0.0
